title: Matias Bilkis
description: "Personal website of Matias Bilkis: quantum technology, machine learning, research papers, talks, coding projects, and blog."
author:
  name: Matias Bilkis
lang: es
default_lang: es
url: "https://matiasbilkis.com"
baseurl: ""
google_analytics: "G-J5XJ3N46W1"
image: "/assets/images/foto_lead.png"
twitter:
  card: summary_large_image

markdown: kramdown
kramdown:
  input: GFM

collections:
  pages:
    output: true
    permalink: /:name

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      lang: es
      layout: post
      permalink: /blog/:title/
      image: "/assets/images/foto_lead.png"
  - scope:
      path: ""
      type: "pages"
    values:
      lang: es
      layout: default
      image: "/assets/images/foto_lead.png"
